"""create base tables

Revision ID: 0519cab312b6
Revises: 
Create Date: 2025-08-22 16:07:57.774460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0519cab312b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('APSA', 'ACONEX', name='sourceenum'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_id'), 'loads', ['id'], unique=False)
    op.create_table('aconex_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=120), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=60), nullable=True),
    sa.Column('function', sa.String(length=120), nullable=True),
    sa.Column('subsystem_text', sa.String(length=255), nullable=True),
    sa.Column('subsystem_code', sa.String(length=60), nullable=True),
    sa.Column('system_no', sa.String(length=60), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('equipment_tag_no', sa.String(length=120), nullable=True),
    sa.Column('date_received', sa.String(length=30), nullable=True),
    sa.Column('revision', sa.String(length=30), nullable=True),
    sa.Column('transmitted', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aconex_core', 'aconex_docs', ['subsystem_code', 'function', 'discipline'], unique=False)
    op.create_index(op.f('ix_aconex_docs_discipline'), 'aconex_docs', ['discipline'], unique=False)
    op.create_index(op.f('ix_aconex_docs_document_no'), 'aconex_docs', ['document_no'], unique=False)
    op.create_index(op.f('ix_aconex_docs_function'), 'aconex_docs', ['function'], unique=False)
    op.create_index(op.f('ix_aconex_docs_subsystem_code'), 'aconex_docs', ['subsystem_code'], unique=False)
    op.create_table('apsa_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cmdic', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=120), nullable=True),
    sa.Column('subsistema', sa.String(length=60), nullable=True),
    sa.Column('disciplina', sa.String(length=10), nullable=True),
    sa.Column('status_bim360', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apsa_core', 'apsa_protocols', ['subsistema', 'disciplina', 'status_bim360'], unique=False)
    op.create_index(op.f('ix_apsa_protocols_codigo_cmdic'), 'apsa_protocols', ['codigo_cmdic'], unique=False)
    op.create_index(op.f('ix_apsa_protocols_disciplina'), 'apsa_protocols', ['disciplina'], unique=False)
    op.create_index(op.f('ix_apsa_protocols_status_bim360'), 'apsa_protocols', ['status_bim360'], unique=False)
    op.create_index(op.f('ix_apsa_protocols_subsistema'), 'apsa_protocols', ['subsistema'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apsa_protocols_subsistema'), table_name='apsa_protocols')
    op.drop_index(op.f('ix_apsa_protocols_status_bim360'), table_name='apsa_protocols')
    op.drop_index(op.f('ix_apsa_protocols_disciplina'), table_name='apsa_protocols')
    op.drop_index(op.f('ix_apsa_protocols_codigo_cmdic'), table_name='apsa_protocols')
    op.drop_index('ix_apsa_core', table_name='apsa_protocols')
    op.drop_table('apsa_protocols')
    op.drop_index(op.f('ix_aconex_docs_subsystem_code'), table_name='aconex_docs')
    op.drop_index(op.f('ix_aconex_docs_function'), table_name='aconex_docs')
    op.drop_index(op.f('ix_aconex_docs_document_no'), table_name='aconex_docs')
    op.drop_index(op.f('ix_aconex_docs_discipline'), table_name='aconex_docs')
    op.drop_index('ix_aconex_core', table_name='aconex_docs')
    op.drop_table('aconex_docs')
    op.drop_index(op.f('ix_loads_id'), table_name='loads')
    op.drop_table('loads')
    # ### end Alembic commands ###
